### ISSUE TITLE
BUG: failed to locate page for Main.Bugs and Fixes.Found Bugs.VeeamONE.Veeam ONE v9\.5 Bugs.WebHome

### ISSUE THREAD

**Issue by daymer** [daymer/xWIKI_Karma#1]
xWIKI_Karma/Comparer_core_v2_0.py
2017-09-25 20:43:13,331 - DEBUG - Starting new HTTP connection (1): wiki.support.veeam.local
2017-09-25 20:43:13,391 - DEBUG - http://wiki.support.veeam.local:80 "GET /api.php?meta=siteinfo%7Cuserinfo%7Cuserinfo&siprop=general%7Cnamespaces&uiprop=groups%7Crights%7Cblockinfo%7Chasmsg&continue=&action=query&format=json HTTP/1.1" 200 None
2017-09-25 20:43:13,442 - INFO - Initialization finished, job started at 2017-09-25 20:43:13.317198
2017-09-25 20:43:13,442 - INFO - Main.Bugs and Fixes.Found Bugs.VeeamONE.Veeam ONE v9\.5 Bugs.WebHome: Task initialized.
2017-09-25 20:43:13,445 - DEBUG - Starting new HTTP connection (1): xwiki.support2.veeam.local
2017-09-25 20:43:13,515 - DEBUG - http://xwiki.support2.veeam.local:80 "GET /rest/wikis/xwiki/spaces/Main/spaces/Bugs%20and%20Fixes/spaces/Found%20Bugs/spaces/VeeamONE/spaces/Veeam%20ONE%20v9%5C.5%20Bugs/pages/WebHome?media=json HTTP/1.1" 404 439
2017-09-25 20:43:13,517 - DEBUG - Starting new HTTP connection (1): xwiki.support2.veeam.local
2017-09-25 20:43:13,561 - DEBUG - http://xwiki.support2.veeam.local:80 "GET /rest/wikis/xwiki/spaces/Main/spaces/Bugs%20and%20Fixes/spaces/Found%20Bugs/spaces/VeeamONE/spaces/pages/Veeam%20ONE%20v9%5C.5%20Bugs?media=json HTTP/1.1" 404 439
Traceback (most recent call last):
  File "C:/Projects/xWIKI_Karma/Comparer_core_v2_0.py", line 180, in <module>
    CurrentPage = PageXWiki(page=title, page_title=real_title, xWikiClient_inst=xWikiClient_inst)
  File "C:\Projects\xWIKI_Karma\Page_mechanics.py", line 62, in __init__
    self.page_id = self.page_from_API['id']
TypeError: 'NoneType' object is not subscriptable

**Comment by daymer** [comment]
same for any page with the dot in it's name

2017-09-29 16:47:48,043 - INFO - Initialization finished, job started at 2017-09-29 16:47:47.863460
2017-09-29 16:47:48,043 - INFO - Main.Bugs and Fixes.Found Bugs.VeeamONE.Veeam ONE v7\.0 Bugs.WebHome: Task initialized.
Traceback (most recent call last):
  File "C:/Projects/xWIKI_Karma/Comparer_core_v2_0.py", line 180, in <module>
    CurrentPage = PageXWiki(page=title, page_title=real_title, xWikiClient_inst=xWikiClient_inst)
  File "C:\Projects\xWIKI_Karma\Page_mechanics.py", line 62, in __init__
    self.page_id = self.page_from_API['id']
TypeError: 'NoneType' object is not subscriptable
172.17.17.183 - - [2017-09-29 16:47:48] "POST / HTTP/1.1" 200 200 0.856340
172.17.17.183 - - [2017-09-29 16:47:48] "POST / HTTP/1.1" 200 242 0.000000

**Comment by daymer** [comment]
Fixed
